src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;

/**
 * @ORM\Entity
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $category_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tags_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", cascade="remove")
     * @OrderBy({"id" = "DESC"})
     */
    private $comments;

    /**
     * Article constructor.
     */
    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(?int $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getTagsId(): ?int
    {
        return $this->tags_id;
    }

    public function setTagsId(?int $tags_id): self
    {
        $this->tags_id = $tags_id;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(?\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    /**
     * Add comment
     *
     * @param \App\Entity\Comment $comment
     *
     * @return Article
     */
    public function addComment(Comment $comment)
    {
        $this->comments[] = $comment;
        return $this;
    }

    /**
     * Remove comment
     *
     * @param \App\Entity\Comment $comment
     */
    public function removeComment(Comment $comment)
    {
        $this->comments->removeElement($comment);
    }

    /**
     * Get comment
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getComments()
    {
        return $this->comments;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="comments")
     * @ORM\JoinColumn(name="article_id", referencedColumnName="id")
     */
    private $article;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Set article
     *
     * @param \App\Entity\Article $article
     *
     * @return Comment
     */
    public function setArticle(Article $article = null)
    {
        $this->article = $article;

        return $this;
    }

    /**
     * Get article
     *
     * @return \App\Entity\Article
     */
    public function getArticle()
    {
        return $this->article;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('author', TextType::class, ['label' => 'Автор'])
            ->add('title', TextType::class, ['label' => 'Заголовок'])
            ->add('content', TextareaType::class, ['label' => 'Контент'])
            ->add('category_id', TextType::class, ['label' => 'Категории'])
            ->add('tags_id', TextType::class, ['label' => 'Метки'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/blog", name="article")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();

        $posts = $em->getRepository(Article::class)->findAll();

        return $this->render('article/index.html.twig', [
            'controller_name' => 'ArticleController',
            'posts' => $posts
        ]);
    }

    /**
     * @Route("/blog/single/{post}", name="single_post")
     */
    public function single(Article $post)
    {

        return $this->render('article/single.html.twig', [
            'post' => $post
        ]);
    }
    /**
     * @Route("/blog/create_post", name="create_post")
     */
    public function create(Request $request)
    {
        $article = new Article();

        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setCreateAt(new \DateTime('now'));

            $em = $this->getDoctrine()->getManager();

            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('article');
        }

        return $this->render('article/form.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/blog/update/{post}", name="update_post")
     */
    public function update(Request $request, Article $post)
    {

        $form = $this->createForm(ArticleType::class, $post, [
            'action' => $this->generateUrl('update_post', [
                'post' => $post->getId()
            ]),
            'method' => 'POST'
        ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setUpdateAt(new \DateTime('now'));

            $em = $this->getDoctrine()->getManager();

            $em->persist($article);
            $em->flush();
            return $this->redirectToRoute('single_post', ['post' => $post->getId()]);

        }

        return $this->render('article/form.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/blog/delete/{post}", name="delete_post")
     */
    public function delete(Article $post)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($post);
        $em->flush();

        return $this->redirectToRoute('article');
    }
}

templates/article/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>CREATE PAGE</h1>

        <div class="container"></div>
    </div>
{% endblock %}

templates/article/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FORM{% endblock %}

{% block body %}

    <div class="container">
        <h1>FORM </h1>
        <div class="col-sm-12">
            {{ form_start(form) }}
            <div class="form_group">
                <label for="textarea">{{ form_label(form.title) }}</label><br>
                {{ form_widget(form.title) }}
            </div>
            <div class="form_group">
                <label for="textarea">{{ form_label(form.author) }}</label><br>
                {{ form_widget(form.author) }}
            </div>
            <div class="form_group">
                <label for="textarea">{{ form_label(form.content) }}</label><br>
                {{ form_widget(form.content) }}
            </div>
            <div class="form_group">
                <label for="textarea">{{ form_label(form.category_id) }}</label><br>
                {{ form_widget(form.category_id) }}
            </div>
            <div class="form_group">
                <label for="textarea">{{ form_label(form.tags_id) }}</label><br>
                {{ form_widget(form.tags_id) }}
            </div>
            <button type="submit">Добавить</button>
            {{ form_end(form) }}
        </div>
    </div>


{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Blog</h1>
            <p class="lead text-muted">My first lessons for learning Symphony. I`m a happy</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Button 1</a>
                <a href="#" class="btn btn-secondary my-2">Button 2</a>
            </p>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                            <div class="card-body">
                                <p class="card-text">
                                    <a href="{{ path('single_post', {'post':post.id}) }}">{{ post.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ path('single_post', {'post':post.id}) }}" class="btn btn-sm btn-default">View</a>
                                        <a href="{{ path('update_post', {'post':post.id}) }}" class="btn btn-sm btn-warning">Edit</a>
                                    </div>
                                    <small class="text-muted">Author: {{ post.author }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

templates/article/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
    <div class="p-3 text-white bg-dark">
        <div class="container">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">{{ post.title }}</h1>
                <p class="lead my-3 text-muted">Posted: {{ post.CreateAt|date("F jS \\a\\t g:ia") }}</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 blog-main">
                <div class="blog-post">
                    {{ post.content }}
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-9"></div>
            <div class="col-md-3">
                <a class="btn btn-warning" href="{{ path('update_post', {'post':post.id}) }}">I</a>
                <a class="btn btn-danger" href="{{ path('delete_post', {'post':post.id}) }}">Х</a>
            </div>
        </div>
        <h2>Comments</h2>
        {% for comment in post.comments %}
            <div class="row">
                <div class="col-md-5">
                    <div class="card-body">
                        <div class="auhtor">
                            Author: {{ comment.author }}
                        </div>
                        <div class="created">
                            Created: {{ comment.createdAt|date("F jS \\a\\t g:ia") }}
                        </div>
                        <div class="content">
                            Content: {{ comment.content }}
                        </div>
                    </div>
                </div>
                <div class="com-md-2">
                    <div class="btn-group">
                        <div class="text-white bg-white"><a class="btn btn-warning" href="{{ path('comment_update_form', {'post':post.id, 'comment':comment.id}) }}">I</a></div>
                        <div class="text-white bg-white"><a class="btn btn-danger" href="{{ path('comment_delete', {'post':post.id, 'comment':comment.id}) }}">Х</a></div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {{ render(controller( 'App\\Controller\\CommentController::create', {'article' : post.id} )) }}


    </div>
{% endblock %}